const ERROR_DEFAULT = 500;
const ERROR_CODE = 400;
const ERROR_UNAUTHORIZED = 401;
const ERROR_FORBIDDEN = 403;
const ERROR_NOT_FOUND = 404;

module.exports = {
  ERROR_DEFAULT,
  ERROR_CODE,
  ERROR_UNAUTHORIZED,
  ERROR_FORBIDDEN,
  ERROR_NOT_FOUND,
};
